Fixed if-body / else-body declarations not going out of scope and wrote test.  Removed work-around in bpr.bps

diff --git a/bin/bpr b/bin/bpr
--- a/bin/bpr
+++ b/bin/bpr
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #
-# Generated from bin/bpr.bps on 2024-01-09T19:17:03.025923581-08:00[America/Los_Angeles] (timestamp 1704856623025)
+# Generated from bin/bpr.bps on 2024-01-10T18:31:31.829370926-08:00[America/Los_Angeles] (timestamp 1704940291829)
 #
 # strict mode header
 set -eEuo pipefail -o posix
@@ -63,9 +63,9 @@ if [ "$1" != "-c" ] && [ "$1" != "--command" ]; then
     if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
 else
     # creates statement, Bashpile line 32
-    declare translationFilename
-    if translationFilename=$(set -o noclobber; java -jar "$jarPath" -c "$2" | tail -1) 2> /dev/null; then
-        trap 'rm -f "$translationFilename"; exit 10' INT TERM EXIT
+    declare translatedFilename
+    if translatedFilename=$(set -o noclobber; java -jar "$jarPath" -c "$2" | tail -1) 2> /dev/null; then
+        trap 'rm -f "$translatedFilename"; exit 10' INT TERM EXIT
         ## wrapped body of creates statement
         # expression statement, Bashpile line 36
         sleep .2
@@ -74,14 +74,14 @@ else
         # expression statement, Bashpile line 38
         shift
         # expression statement, Bashpile line 39
-        chmod 755 $translationFilename
+        chmod 755 $translatedFilename
         # creates statement, Bashpile line 41
-        if (set -o noclobber; "$translationFilename" "$@" 2>&1 | tee "bpr.log") 2> /dev/null; then
-            trap 'rm -f "$translationFilename" bpr.log; exit 10' INT TERM EXIT
+        if (set -o noclobber; "$translatedFilename" "$@" 2>&1 | tee "bpr.log") 2> /dev/null; then
+            trap 'rm -f "$translatedFilename" bpr.log; exit 10' INT TERM EXIT
             ## wrapped body of creates statement
             if cat bpr.log | grep -E 'unexpected EOF|syntax error|command not found' > /dev/null 2>&1; then
                 # expression statement, Bashpile line 43
-                "$translationFilename" "$@"
+                "$translatedFilename" "$@"
             fi
             ## end of wrapped body of creates statement
             rm -f bpr.log
@@ -94,11 +94,11 @@ else
         declare -i __bp_exitCode=$?
         if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
         ## end of wrapped body of creates statement
-        rm -f "$translationFilename"
+        rm -f "$translatedFilename"
         trap - INT TERM EXIT
     else
-        printf "Failed to create translationFilename correctly.  Output from attempted creation:\n$translationFilename"
-        rm -f "$translationFilename"
+        printf "Failed to create translatedFilename correctly.  Output from attempted creation:\n$translatedFilename"
+        rm -f "$translatedFilename"
         exit 1
     fi
     declare -i __bp_exitCode=$?
