Implemented better error handling.  Removed unneeded and slow file system DFSs in BashpileMainIntegrationTest.  Created test to verify error handling.

diff --git a/bin/bpr b/bin/bpr
--- a/bin/bpr
+++ b/bin/bpr
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
 #
-# Generated from bin/bpr.bps on 2023-08-10T13:56:58.587943283-07:00[America/Los_Angeles] (timestamp 1691701018587)
+# Generated from bin/bpr.bps on 2023-08-10T21:40:58.268796354-07:00[America/Los_Angeles] (timestamp 1691728858268)
 #
 # strict mode header
-set -euo pipefail -o posix
+set -eEuo pipefail -o posix
 export IFS=$'\n\t'
+declare s
+trap 's=$?; echo "$0: Error on line $LINENO: $BASH_COMMAND"; exit $s' ERR
 # assign statement, Bashpile line 7
 export dir
 dir=$(dirname "${BASH_SOURCE[0]}")
