bpr.bps now has common logic refactored out with arguments[all].  Normal lists handle list[all] syntax.

diff --git a/bin/bpr b/bin/bpr
--- a/bin/bpr
+++ b/bin/bpr
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #
-# Generated from bin/bpr.bps on 2024-03-09T21:12:05.792656620-08:00[America/Los_Angeles] (timestamp 1710047525792)
+# Generated from bin/bpr.bps on 2024-03-28T16:18:55.340180686-07:00[America/Los_Angeles] (timestamp 1711667935340)
 #
 # strict mode header
 set -eEuo pipefail -o posix
@@ -49,92 +49,86 @@ if ! ${commandMode} && [ -z "${1+default}" ]; then
     java -jar "$jarPath"
     exit $?
 fi
+set +u
+# function declaration, Bashpile line 39
+runTranslation () {
+    declare -r translatedFilename=$1; declare -x IFS=$' '; read -r -a args <<< "$2"; declare -x IFS=$'\n\t';
+    # creates statement, Bashpile line 41
+    if (set -o noclobber; ./"$translatedFilename" "${args[@]}" 2>&1 | tee "bpr.log") 2> /dev/null; then
+        trap 'rm -f bpr.log; exit 10' INT TERM EXIT
+        ## wrapped body of creates statement
+        if cat bpr.log | grep -E 'unexpected EOF|syntax error|command not found' > /dev/null 2>&1; then
+            # expression statement, Bashpile line 44
+            ./"$translatedFilename" "${args[@]}"
+        fi
+        ## end of wrapped body of creates statement
+        rm -f bpr.log
+        trap - INT TERM EXIT
+    else
+        printf "Failed to create bpr.log correctly, script output was:\n"
+        cat bpr.log
+        rm -f bpr.log
+        return 1
+    fi
+    declare -i __bp_exitCode=$?
+    if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
+}
 if ! ${commandMode}; then
     if [ "${translatedFilename}" == "command.bpt" ]; then
-        # reassign statement, Bashpile line 42
+        # reassign statement, Bashpile line 50
         translatedFilename=$1.bpt
         if [ -e "${translatedFilename}" ]; then
-            # print statement, Bashpile line 44
+            # print statement, Bashpile line 52
             printf "Will not overwrite ${translatedFilename}\n"
             exit 1
         fi
     fi
-    # creates statement, Bashpile line 46
+    # creates statement, Bashpile line 54
     if (set -o noclobber; java -jar "$jarPath" --outputFile="$translatedFilename" "$1") 2> /dev/null; then
         trap 'rm -f "$translatedFilename"; exit 10' INT TERM EXIT
         ## wrapped body of creates statement
         shift
-        # print statement, Bashpile line 48
+        # print statement, Bashpile line 56
         printf "Start of ${translatedFilename}\n"
         chmod 755 $translatedFilename
-        # creates statement, Bashpile line 52
-        if (set -o noclobber; ./"$translatedFilename" "$@" 2>&1 | tee "bpr.log") 2> /dev/null; then
-            trap 'rm -f "$translatedFilename" bpr.log; exit 10' INT TERM EXIT
-            ## wrapped body of creates statement
-            if cat bpr.log | grep -E 'unexpected EOF|syntax error|command not found' > /dev/null 2>&1; then
-                # expression statement, Bashpile line 55
-                ./"$translatedFilename" "$@"
-            fi
-            ## end of wrapped body of creates statement
-            rm -f bpr.log
-            trap - INT TERM EXIT
-        else
-            printf "Failed to create pr.log correctly."
-            rm -f bpr.log
-            exit 1
-        fi
-        declare -i __bp_exitCode=$?
-        if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
+        # expression statement, Bashpile line 58
+        runTranslation "${translatedFilename}" "$@"
         ## end of wrapped body of creates statement
         rm -f "$translatedFilename"
         trap - INT TERM EXIT
     else
-        printf "Failed to create translatedFilename correctly."
+        printf "Failed to create translatedFilename correctly, script output was:\n"
+        cat "$translatedFilename"
         rm -f "$translatedFilename"
         exit 1
     fi
     declare -i __bp_exitCode=$?
     if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
 else
-    # assign statement, Bashpile line 58
+    # assign statement, Bashpile line 61
     declare commandString
     if [ -n "${1+default}" ]; then
-        # reassign statement, Bashpile line 60
+        # reassign statement, Bashpile line 63
         commandString=$1
         shift
     else
-        # reassign statement, Bashpile line 63
+        # reassign statement, Bashpile line 66
         commandString=$(cat -)
     fi
-    # creates statement, Bashpile line 64
+    # creates statement, Bashpile line 67
     if (set -o noclobber; java -jar "$jarPath" --outputFile="$translatedFilename" -c "$commandString" 1>/dev/null) 2> /dev/null; then
         trap 'rm -f "$translatedFilename"; exit 10' INT TERM EXIT
         ## wrapped body of creates statement
         sleep .2
         chmod 755 $translatedFilename
-        # creates statement, Bashpile line 69
-        if (set -o noclobber; ./"$translatedFilename" "$@" 2>&1 | tee "bpr.log") 2> /dev/null; then
-            trap 'rm -f "$translatedFilename" bpr.log; exit 10' INT TERM EXIT
-            ## wrapped body of creates statement
-            if cat bpr.log | grep -E 'unexpected EOF|syntax error|command not found' > /dev/null 2>&1; then
-                # expression statement, Bashpile line 71
-                ./"$translatedFilename" "$@"
-            fi
-            ## end of wrapped body of creates statement
-            rm -f bpr.log
-            trap - INT TERM EXIT
-        else
-            printf "Failed to create pr.log correctly."
-            rm -f bpr.log
-            exit 1
-        fi
-        declare -i __bp_exitCode=$?
-        if [ "$__bp_exitCode" -ne 0 ]; then exit "$__bp_exitCode"; fi
+        # expression statement, Bashpile line 71
+        runTranslation "${translatedFilename}" "$@"
         ## end of wrapped body of creates statement
         rm -f "$translatedFilename"
         trap - INT TERM EXIT
     else
-        printf "Failed to create translatedFilename correctly."
+        printf "Failed to create translatedFilename correctly, script output was:\n"
+        cat "$translatedFilename"
         rm -f "$translatedFilename"
         exit 1
     fi
